#!/usr/bin/env python

# This file is part of Fail2Ban.
#
# Fail2Ban is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fail2Ban is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fail2Ban; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Author: Cyril Jaquier
# 
# $Revision: 1.4.2.5 $

__author__ = "Cyril Jaquier"
__version__ = "$Revision: 1.4.2.5 $"
__date__ = "$Date: 2005/08/04 20:51:14 $"
__copyright__ = "Copyright (c) 2004 Cyril Jaquier"
__license__ = "GPL"

import sys, traceback, logging, time

# Appends our own modules path.
sys.path.append("/usr/share/fail2ban")

# Now we can import our modules.
import fail2ban
from utils.pidlock import PIDLock
from utils.process import ExternalError

# Start the application. Handle all the unhandled exceptions
# yoh: I don't think that this parameters need to be configured
#      and probably maxRestarts should be removed
legitRestartTime = 10				 # legitimate minimal restart time
maxRestarts = 100			  # max number of times to perform restart

lastRestartTime = time.time()
restarts = 0

# Get the instance of the logger.
logSys = logging.getLogger("fail2ban")

# Get PID lock file instance
pidLock = PIDLock()

try:
	while True:
		restarts += 1
		try:
			fail2ban.main(restarts>1)
		except ExternalError, e:
			# There went something wrong while dealing with Iptables. May be chain got
			# removed?
			logSys.error("Fail2Ban got a problem: " + e.__str__())
			if (time.time() - lastRestartTime > legitRestartTime) and (restarts < maxRestarts):
				logSys.error("Restarting for the %d time "%restarts)
				lastRestartTime = time.time()
			else:
				logSys.error("Exiting: restarts follow too often, or too many restart attempts")
				sys.exit(0)
except SystemExit:
	# We called sys.exit(). Nothing wrong so just pass
	pass
except Exception, e:
	# Print the exception data
	(type, value, tb) = sys.exc_info()
	tbStack = traceback.extract_tb(tb)
	logSys.error("Fail2Ban got an unhandled exception and died.")
	logSys.error("Type: " + `type.__name__` + "\n" +
				 "Value: " + `e.args` + "\n" +
				 "TB: " + `tbStack`)

# Remove the PID lock file. Should close #1239562
pidLock.remove()
logSys.info("Exiting...")
logging.shutdown()
	
